### ISSUE TITLE
Regex Basics dead link

### ISSUE THREAD

**Issue by sjwakeman** [learn-co-curriculum/regex-basics-readme#9]
The following link RegEx Golf 
https://alf.nu/UnknownHost/regex.alf.nu

Unknown Host

Amazon just killed my old name server. Sorry. These will be back soon-ish.

Looking for regex.alf.nu?

The amazing Internet Archive might have a copy for now. It's playable, at least in Chrome.

Complaints to @steike.

**Comment by curiositypaths** [comment]
Hi There,

Thank you for notifying us. All the links appear to be working now.

As always, thank you for contributing 💙
